### ISSUE TITLE
Save Literature Notes to md is broken

### ISSUE THREAD

**Issue by schwab** [schwab/notetaker_ai#5]
Traceback (most recent call last):
  File "/home/mcstar/whisper/cli.py", line 439, in <module>
    menu()
  File "/home/mcstar/whisper/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcstar/whisper/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/mcstar/whisper/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcstar/whisper/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/mcstar/whisper/cli.py", line 431, in menu
    literature_note_menu()
  File "/home/mcstar/whisper/cli.py", line 294, in literature_note_menu
    url = convert_url(video_url, time_start)
  File "/home/mcstar/whisper/cli.py", line 199, in convert_url
    req.prepare_url(url, params)
  File "/home/mcstar/whisper/venv/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'redis_vector_index_training.mp3': No scheme supplied. Perhaps you meant https://redis_vector_index_training.mp3?

**Comment by schwab** [comment]
Fixed with conversion to use redis as the backend.
